### ISSUE TITLE
npm install is not working

### ISSUE THREAD

**Issue by ashwin31** [Meesam/IssueTracker#2]
$ npm install
npm WARN package.json issuetracker@1.0.0 No repository field.

**Comment by Meesam** [comment]
hi ashwin , can you please explain a bit , i can't understand what is the issue.

**Comment by Meesam** [comment]
hi ashiwin , this issue has been resolved, kindly check it,

Note :- Please ignore " npm WARN package.json issuetracker@1.0.0 No README data "  this warning on npm intall.
